wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741244140
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation_function:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 16
initialisation:
  desc: null
  value: random
learning_rate:
  desc: null
  value: 0.001
number_of_epochs:
  desc: null
  value: 5
number_of_hidden_layers:
  desc: null
  value: 3
size_of_every_hidden_layer:
  desc: null
  value: 128
