wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.011068274810421542
beta1:
  value: 0.9909599312399968
beta2:
  value: 0.9957158496314183
epochs:
  value: 15
epsilon:
  value: 4.4685910049754015e-06
hidden_size:
  value: 128
learning_rate:
  value: 4.494403090927779e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9379048779085638
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: Xavier
