wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.034514563915777244
beta1:
  value: 0.9889718744035632
beta2:
  value: 0.995276365303322
epochs:
  value: 15
epsilon:
  value: 3.23942570981378e-06
hidden_size:
  value: 128
learning_rate:
  value: 2.568719005902283e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8949577749936928
num_layers:
  value: 6
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
