wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta:
  value: 0.06958143149552884
beta1:
  value: 0.9815747648404544
beta2:
  value: 0.9959233222746448
epochs:
  value: 10
epsilon:
  value: 2.249856009488587e-06
hidden_size:
  value: 64
learning_rate:
  value: 1.9753117009550936e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.965974796642986
num_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: random
