wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.07014189974931961
beta1:
  value: 0.9818967654717548
beta2:
  value: 0.9955367244927166
epochs:
  value: 10
epsilon:
  value: 2.9418340808779944e-06
hidden_size:
  value: 128
learning_rate:
  value: 7.453432193381975e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8672184348463534
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
