wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.95
beta1:
  value: 0.8
beta2:
  value: 0.9999
epochs:
  value: 5
epsilon:
  value: 1.0e-06
hidden_size:
  value: 512
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
