wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.8
beta2:
  value: 0.9
epochs:
  value: 5
epsilon:
  value: 1.0e-05
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
momentum:
  value: 0.1
num_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: random
