wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741490370
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 64
beta:
  desc: null
  value: 0.08915593718836644
beta1:
  desc: null
  value: 0.9899383950850827
beta2:
  desc: null
  value: 0.9956203407479656
epochs:
  desc: null
  value: 15
epsilon:
  desc: null
  value: 1.3236781050492196e-06
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0004642697887858732
loss:
  desc: null
  value: cross_entropy
momentum:
  desc: null
  value: 0.9284545638008962
num_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: rmsprop
weight_decay:
  desc: null
  value: 0.001
weight_init:
  desc: null
  value: Xavier
