wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741479071
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 16
beta:
  desc: null
  value: 0.08897247942464771
beta1:
  desc: null
  value: 0.9860431523082992
beta2:
  desc: null
  value: 0.996272977664484
epochs:
  desc: null
  value: 15
epsilon:
  desc: null
  value: 1.2327268880529211e-06
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0004832120374988159
loss:
  desc: null
  value: cross_entropy
momentum:
  desc: null
  value: 0.9843132796223536
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: nag
weight_decay:
  desc: null
  value: 0.001
weight_init:
  desc: null
  value: Xavier
