wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.5
beta1:
  value: 0.99
beta2:
  value: 0.99
epochs:
  value: 5
epsilon:
  value: 1.0e-06
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
