wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta:
  value: 0.95
beta1:
  value: 0.8
beta2:
  value: 0.9
epochs:
  value: 15
epsilon:
  value: 1.0e-05
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 6
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: random
