wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.9
epochs:
  value: 5
epsilon:
  value: 0.0001
hidden_size:
  value: 128
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 3
optimizer:
  value: gd
weight_decay:
  value: 0.5
weight_init:
  value: random
