wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.05
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 10
epsilon:
  value: 1.0e-06
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
