wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.05
beta1:
  value: 0.99
beta2:
  value: 0.999
epochs:
  value: 10
epsilon:
  value: 1.0e-05
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
