wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.1
beta1:
  value: 0.99
beta2:
  value: 0.99
epochs:
  value: 10
epsilon:
  value: 1.0e-05
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
