wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 5
epsilon:
  value: 1.0e-05
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.1
num_layers:
  value: 6
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
