wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.1
beta1:
  value: 0.99
beta2:
  value: 0.999
epochs:
  value: 15
epsilon:
  value: 1.0e-06
hidden_size:
  value: 32
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
