wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.08649791363453047
beta1:
  value: 0.9838583242011196
beta2:
  value: 0.9950398410361716
epochs:
  value: 15
epsilon:
  value: 1.9037743508111573e-06
hidden_size:
  value: 128
learning_rate:
  value: 1.0580892633995984e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8166680460717108
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
