wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.04718469332138036
beta1:
  value: 0.9811127340245585
beta2:
  value: 0.99677919924962
epochs:
  value: 15
epsilon:
  value: 7.763004814880777e-06
hidden_size:
  value: 32
learning_rate:
  value: 5.8086446587068343e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8377293153632894
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
