wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.03629976154369056
beta1:
  value: 0.9866556370523148
beta2:
  value: 0.9963313825552146
epochs:
  value: 10
epsilon:
  value: 7.777760188761132e-06
hidden_size:
  value: 128
learning_rate:
  value: 2.693548944514078e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8441257347403253
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
