wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.04196385545094778
beta1:
  value: 0.9851972926596578
beta2:
  value: 0.9983378800596244
epochs:
  value: 15
epsilon:
  value: 8.224913535912627e-06
hidden_size:
  value: 128
learning_rate:
  value: 5.772926483750339e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9378057828145796
num_layers:
  value: 6
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
