wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.02635834487772818
beta1:
  value: 0.9847316100089738
beta2:
  value: 0.995360509472008
epochs:
  value: 15
epsilon:
  value: 3.8270173041544734e-06
hidden_size:
  value: 128
learning_rate:
  value: 2.0191381146952948e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8429008006236242
num_layers:
  value: 6
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
