wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.02020573116299082
beta1:
  value: 0.9812785155772292
beta2:
  value: 0.9996838975408704
epochs:
  value: 15
epsilon:
  value: 7.20446610931939e-06
hidden_size:
  value: 32
learning_rate:
  value: 5.719627615717749e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9218061898513016
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
