wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.02279107500482986
beta1:
  value: 0.9859196714760564
beta2:
  value: 0.9972623655851626
epochs:
  value: 10
epsilon:
  value: 6.871181502935947e-06
hidden_size:
  value: 128
learning_rate:
  value: 8.08167695277373e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8520273788900447
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
