wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.045966726051173856
beta1:
  value: 0.9848950398135412
beta2:
  value: 0.996705323343997
epochs:
  value: 10
epsilon:
  value: 4.448759555906078e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.000490391631236213
loss:
  value: mean_squared_error
momentum:
  value: 0.8119596694819334
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
