wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.09194180831691837
beta1:
  value: 0.9807865088716908
beta2:
  value: 0.9980065510644393
epochs:
  value: 15
epsilon:
  value: 6.556654307659129e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.0002316711028424266
loss:
  value: mean_squared_error
momentum:
  value: 0.9688350002308868
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
