wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.0684733027061539
beta1:
  value: 0.9857520044963584
beta2:
  value: 0.9966515266626144
epochs:
  value: 15
epsilon:
  value: 8.961933794868149e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.0001053937788872317
loss:
  value: mean_squared_error
momentum:
  value: 0.931508969605141
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
