wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.08953166564178167
beta1:
  value: 0.9819337006463984
beta2:
  value: 0.9950126461418692
epochs:
  value: 10
epsilon:
  value: 8.260274650261937e-06
hidden_size:
  value: 64
learning_rate:
  value: 3.33833165689063e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.8012730060465654
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
