wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.05469526740037658
beta1:
  value: 0.9803107212545744
beta2:
  value: 0.9956317724423857
epochs:
  value: 15
epsilon:
  value: 1.773928922433444e-06
hidden_size:
  value: 128
learning_rate:
  value: 4.818800606251087e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9215926943176728
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
