wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.035997979510856905
beta1:
  value: 0.9808504282880628
beta2:
  value: 0.998168237674534
epochs:
  value: 15
epsilon:
  value: 4.7002470857558e-06
hidden_size:
  value: 64
learning_rate:
  value: 9.35458891148469e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9387212609457104
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
