wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.016516348387805885
beta1:
  value: 0.981737063119684
beta2:
  value: 0.9984371357274968
epochs:
  value: 15
epsilon:
  value: 4.0686560534803586e-06
hidden_size:
  value: 128
learning_rate:
  value: 2.66434317038548e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9197213886261854
num_layers:
  value: 6
optimizer:
  value: nadam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
