wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
beta:
  value: 0.020390523715604528
beta1:
  value: 0.9803980933999612
beta2:
  value: 0.9958027371724796
epochs:
  value: 10
epsilon:
  value: 8.14110928436036e-06
hidden_size:
  value: 128
learning_rate:
  value: 6.403874377405507e-05
loss:
  value: mean_squared_error
momentum:
  value: 0.9459365071163586
num_layers:
  value: 6
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
