_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation_function:
    value: sigmoid
batch_size:
    value: 128
initialisation:
    value: random
learning_rate:
    value: 0.01
number_of_epochs:
    value: 5
number_of_hidden_layers:
    value: 3
size_of_every_hidden_layer:
    value: 16
