wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
beta:
  value: 0.05
beta1:
  value: 0.8
beta2:
  value: 0.999
epochs:
  value: 15
epsilon:
  value: 0.0001
hidden_size:
  value: 512
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 4
optimizer:
  value: gd
weight_decay:
  value: 0
weight_init:
  value: random
