wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.5
beta1:
  value: 0.8
beta2:
  value: 0.999
epochs:
  value: 10
epsilon:
  value: 1.0e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 6
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
