wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741569448
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 32
beta:
  desc: null
  value: 0.020472310520879708
beta1:
  desc: null
  value: 0.9826630039466816
beta2:
  desc: null
  value: 0.999741390676607
epochs:
  desc: null
  value: 15
epsilon:
  desc: null
  value: 1.5630529162873828e-06
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.00033724595499661566
loss:
  desc: null
  value: mean_squared_error
momentum:
  desc: null
  value: 0.960342611664239
num_layers:
  desc: null
  value: 6
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: Xavier
