wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.06333478700627908
beta1:
  value: 0.983819396655386
beta2:
  value: 0.9963732760684264
epochs:
  value: 10
epsilon:
  value: 2.901592903337258e-06
hidden_size:
  value: 64
learning_rate:
  value: 4.138404690437241e-05
loss:
  value: cross_entropy
momentum:
  value: 0.960994041927872
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
