wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.06256571114794876
beta1:
  value: 0.9944252534014002
beta2:
  value: 0.998964174699631
epochs:
  value: 10
epsilon:
  value: 1.0988381232775222e-06
hidden_size:
  value: 64
learning_rate:
  value: 1.4694193784414002e-05
loss:
  value: cross_entropy
momentum:
  value: 0.8221629581648479
num_layers:
  value: 5
optimizer:
  value: momentum
weight_decay:
  value: 0.0001
weight_init:
  value: random
