wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.04767206676941771
beta1:
  value: 0.9864003696680278
beta2:
  value: 0.9954277859432202
epochs:
  value: 10
epsilon:
  value: 2.4505790039127124e-06
hidden_size:
  value: 128
learning_rate:
  value: 7.650542595316507e-05
loss:
  value: cross_entropy
momentum:
  value: 0.9731775941212372
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.001
weight_init:
  value: random
