wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.05971785910759169
beta1:
  value: 0.991900972419372
beta2:
  value: 0.995662491668532
epochs:
  value: 15
epsilon:
  value: 4.247752316412051e-06
hidden_size:
  value: 128
learning_rate:
  value: 1.713644790889834e-05
loss:
  value: cross_entropy
momentum:
  value: 0.8420186650247148
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
