wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.08819888205675755
beta1:
  value: 0.9925513247891518
beta2:
  value: 0.9968764632644128
epochs:
  value: 15
epsilon:
  value: 3.8307907709113016e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.0004097528385750248
loss:
  value: cross_entropy
momentum:
  value: 0.952072972715858
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
