wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.03433057878059331
beta1:
  value: 0.988492288303636
beta2:
  value: 0.9959525115406204
epochs:
  value: 15
epsilon:
  value: 3.043496177036336e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.00012623893706970184
loss:
  value: cross_entropy
momentum:
  value: 0.950608372678629
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
