_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 16
beta:
    value: 0.95
beta1:
    value: 0.8
beta2:
    value: 0.9
epochs:
    value: 15
epsilon:
    value: 1e-05
hidden_size:
    value: 64
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
momentum:
    value: 0.5
num_layers:
    value: 6
optimizer:
    value: sgd
weight_decay:
    value: 0.5
weight_init:
    value: random
