wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741491820
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 64
beta:
  desc: null
  value: 0.017832002124649637
beta1:
  desc: null
  value: 0.9891070707748816
beta2:
  desc: null
  value: 0.9964478924462652
epochs:
  desc: null
  value: 15
epsilon:
  desc: null
  value: 4.312895924937286e-06
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0004103173828853866
loss:
  desc: null
  value: cross_entropy
momentum:
  desc: null
  value: 0.9524518152036966
num_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: nadam
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: Xavier
