wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.19.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741572890
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.19.7
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 16
beta:
  desc: null
  value: 0.04589134125879976
beta1:
  desc: null
  value: 0.9817501806261468
beta2:
  desc: null
  value: 0.9952633013104952
epochs:
  desc: null
  value: 10
epsilon:
  desc: null
  value: 8.574696579336792e-06
hidden_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.00023599310758409456
loss:
  desc: null
  value: mean_squared_error
momentum:
  desc: null
  value: 0.9081858521057236
num_layers:
  desc: null
  value: 6
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.0005
weight_init:
  desc: null
  value: Xavier
